name: negbio3.7
channels:
  - anaconda
  - conda-forge
  - auto
dependencies:
  - python=3.7
  - docutils=0.14
  - docopt=0.6.2
  - pytest=4.2.0
  - networkx=2.2
  - ply=3.11
  - tqdm=4.31
  - nltk=3.4
  - numpy=1.16
  - jpype1=0.6.3
  - pip:
    - bioc==1.3.1
    - pystanforddependencies==0.3.1
    - bllipparser==2016.9.11
    - pymetamap==0.1
